apiVersion: v1
kind: Namespace
metadata:
  name: microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: microservice
  labels:
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: ghcr.io/lreimer/nextgen-iac-pulumi-java:main
        ports:
        - name: http
          containerPort: 10000
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: microservice
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer