name: Pulumi Up

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Authenticate with Google Cloud so we can deploy to the cluster
    - name: 'Authenticate with Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
       project_id: ${{ secrets.GKE_PROJECT }}
       credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: nextgen-iac-pulumi-java
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}